export const PLACEHOLDERS = [
  "create a pricing table with toggle",
  "create a gradient button with hover effect",
  "create a product card with image hover zoom",
  "create a search bar with autocomplete",
  "create a notification toast",
  "create a dark mode toggle",
  "create a progress bar with animation",
  "create a modal with a close button",
  "create a dropdown menu with hover effect",
  "create a card with a shadow effect",
  "create a button with a ripple effect",
  "create a form with validation",
  "create a table with pagination",
];
